name: Deploy App

on:
  push:
    branches:
      - main  # Change this to match your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can change the runner environment if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2  # Use the appropriate Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up database
        run: |
          python manage.py db init
          python manage.py db migrate
          python manage.py db upgrade

      - name: Run Flask app
        run: python routes.py
